name: smart_skeleton_loader_example
description: Example app for smart_skeleton_loader package
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  smart_skeleton_loader:
    path: ../
  connectivity_plus: ^5.0.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
